# Generated by Django 4.0.1 on 2022-02-07 10:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('prodi', models.CharField(choices=[('Sistem Informasi', 'Sistem Informasi'), ('Teknik Informatika', 'Teknik Informatika'), ('Matematika', 'Matematika'), ('Manaajemen', 'Manajemen'), ('Ekonomi Pembangunan', 'Ekonomi Pembangunan'), ('Pendidikan Guru Sekolah Dasar', 'Pendidikan Guru Sekolah Dasar')], default='Sistem Informasi', max_length=35)),
                ('nim', models.BigIntegerField(unique=True)),
                ('email_aktif', models.EmailField(max_length=40, unique=True)),
                ('tgl_lahir', models.DateField()),
            ],
        ),
    ]
