# Generated by Django 4.0.1 on 2022-01-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('prodi', models.CharField(choices=[('SI', 'Sistem Informasi'), ('TI', 'Teknik Informatika'), ('MTK', 'Matematika'), ('MNJ', 'Manajemen'), ('EP', 'Ekonomi Pembangunan'), ('PGSD', 'Pendidikan Guru Sekolah Dasar')], default='Sistem Informasi', max_length=5)),
                ('nim', models.IntegerField(unique=True)),
                ('email_aktif', models.EmailField(max_length=40, unique=True)),
                ('tgl_lahir', models.DateField()),
            ],
        ),
    ]
