# Generated by Django 4.0.1 on 2022-01-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nim',
            field=models.BigIntegerField(unique=True),
        ),
    ]
